name: Futural

on:
  workflow_dispatch:
  workflow_call:
  pull_request:
    types:
      - opened
      - synchronize
  push:
    branches:
      - '19*'

jobs:
  all:
    uses: tawasta/github-workflows/.github/workflows/odoo-19-futural.yml@main
    secrets: inherit
